# Generated by Django 6.0 on 2026-01-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recentscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentscan',
            name='title',
            field=models.CharField(default=0, max_length=260),
            preserve_default=False,
        ),
    ]
